[workspace]
authors = ["rdebrand <richard.hildebrandt@tum.de>"]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "legofmt"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[feature.base.dependencies]
python = ">=3.13.0,<3.15"
pytorch = ">=2.10"
pyg4lego = { git = "https://github.com/lego-erc/pyg4lego.git" }
numpy = "*"
matplotlib = "*"
lightning = "*"
schedulefree = ">=1.4.1"
pip = ">=25.3,<26"
ipykernel = "*"
corner = "*"

[feature.base.target.linux-64.dependencies]
pytorch-cuda = "12.*"

[feature.base.pypi-dependencies]
flow-matching = ">=1.0.10"
legofmt = { path = ".", editable = true }

[feature.modern.pypi-dependencies]
x-transformers = "==2.17.9"

[feature.legacy.pypi-dependencies]
x-transformers = "==2.14.2"

[feature.train.dependencies]
comet-ml = "*"
uv = "*"

[feature.train.activation]
scripts = ["scripts/train_setup.sh"]

[environments]
default = ["base", "modern"]
legacy = ["base", "legacy"]
train = { features = ["base", "modern", "train"], no-default-feature = true }
train-legacy = { features = ["base", "legacy", "train"], no-default-feature = true }
