[workspace]
authors = ["rdebrand <richard.hildebrandt@tum.de>"]
channels = ["conda-forge"]
name = "legofmt"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]

[workspace.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu128"]

[feature.base.dependencies]
python = ">=3.13.0,<3.15"
numpy = "*"
matplotlib = "*"
lightning = "*"
schedulefree = ">=1.4.1"
pip = ">=25.3,<26"
ipykernel = "*"
corner = "*"

[feature.geant4.dependencies]
pyg4lego = { git = "https://github.com/lego-erc/pyg4lego.git" }

[feature.base.pypi-dependencies]
torch = ">=2.10"
flow-matching = ">=1.0.10"
legofmt = { path = ".", editable = true }

[feature.modern.pypi-dependencies]
x-transformers = "==2.17.9"

[feature.legacy.pypi-dependencies]
x-transformers = "==2.14.2"

[feature.train.dependencies]
comet-ml = "*"
uv = "*"

[feature.train.activation]
scripts = ["scripts/train_setup.sh"]

[environments]
default = ["base", "modern"]
geant4 = ["base", "modern", "geant4"]
legacy = ["base", "legacy"]
legacy-geant4 = ["base", "legacy", "geant4"]
train = { features = ["base", "modern", "train"], no-default-feature = true }
train-legacy = { features = ["base", "legacy", "train"], no-default-feature = true }
train-geant4 = { features = ["base", "modern", "train", "geant4"], no-default-feature = true }
train-legacy-geant4 = { features = ["base", "legacy", "train", "geant4"], no-default-feature = true }
