[workspace]
authors = ["rdebrand <richard.hildebrandt@tum.de>"]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "legofmt"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks.build]
args = [
  { "arg" = "mode", "default" = "" },
]
cmd = "{{ mode }} pip install ."

[dependencies]
python = ">=3.14.0,<3.15"

[pypi-dependencies]
numpy = ">=2.3.5"
matplotlib = ">=3.10.7"
torch = ">=2.9.1"
flow-matching = ">=1.0.10"
lightning = ">=2.5.6"
schedulefree = ">=1.4.1"
torch-lap-cuda = ">=0.0.3"
x-transformers = ">=2.11.23"
pip = ">=25.3,<26"
ipykernel = "*"
corner = "*"
legofmt = { path = ".", editable = true }
